### ISSUE TITLE
FASE I: Extracción de Datos de API de MoviesDataset

### ISSUE THREAD

**Issue by MRocioG** [Adalab/proyecto-da-promo-F-modulo-2-team-4#16]
La información de la API deberá ser **almacenada en una lista de tuplas**. 

Cada tupla corresponderá a una película:
[("Pelicula", "Titanic", 1997, 12, "abc123"),
 ("Pelicula", "Los Gonnies", 1985, 6, "abc456")]

En esta fase, usaremos la API de MoviesDataset, que contiene una gran cantidad de información sobre películas, incluyendo detalles como títulos, géneros, años de lanzamiento y más. 

Vuestra tarea será hacer solicitudes a esta API y extraer información relevante sobre las películas. En concreto tendreis que sacar la siguiente información:
 - Películas desde el 1990 hasta la actualidad.
 - Películas que pertenezcan a los siguientes géneros: Drama, Comedy, Action, Fantasy, Horror, Mystery, Romance, Thriller.
 - De cada una de las películas tendreis que sacar la siguiente información:
                     *Tipo (si es corto o película).
                     *Nombre de la película o el corto.
                     *Año de estreno de la película o corto.
                     *Mes de estreno de la película o corto.
                     *Id de la película.
siguiente ejemplo:
[("Pelicula", "Titanic", 1997, 12, "abc123"), ("Pelicula", "Los Gonnies", 1985, 6, "abc456")

**Comment by MRocioG** [comment]
Tenemos localizados todos los filtros de la web

bugs en tarjetas

**Comment by clarasdata** [comment]
**BLOQUEO CON LA API**

Hemos hecho una función a partir de la cual se puden sacacar los datos por año partiendo por genero. Dentro de la función  se ha definido que filtre sólo las películas y cortos.

Con la url:
url = f"https://moviesdatabase.p.rapidapi.com/titles?year={año}&genre={genero}&page={pagina}"

Por defecto salen 10 resultados por página con el siguiente número de pelis por género:
- Drama: 177
- Comedy : 161
- Romance: 90
- Action: 90
- Fantasia: 48
- Mystery:
- Horror:
- Thriller:


En cambio, si a la url le ponemos un límite de 50:
url = f"https://moviesdatabase.p.rapidapi.com/titles?year={año}&genre={genero}&page={pagina}&limit=50"

- Drama: 421
- Comedy: 257

-  Pero cuando se busca los valores de Mistery, Horror, Fantasy, Thriller, Action: no devuelve nada

- Romance: 57 (menos que cuando había 10 por página!)


Revisamos el código y parece estar correcto. Decidimos seguir adelante con éstos dados, y si tenemos tiempo, buscaremos la solución.

**Comment by MRocioG** [comment]
Hecho
